version: '3'

services:

  dev:
    image: ${DEV_IMAGE:-python:3.6}
    working_dir: /opt/app
    command: sh run-dev.sh
    environment:
      FLASK: ${FLASK:-0.12.2}
      CHECK_STYLE: ${CHECK_STYLE:-yes}
      RUN_TEST: ${RUN_TEST:-yes}
    volumes:
      - .:/opt/app
